before:
 - bundle exec berks install --path ./cookbooks
after:
 - bundle exec rake spec

environments:
  development:
    nodes:
      web:
        run_list:
        - recipe[rvm::system]
        - recipe[nginx::source]
        - recipe[user]
        host: 33.33.230.196
        user: vagrant
        password: vagrant
        vagrant:
          IP: 33.33.230.196
          cpu: 1
          memory: 256
